// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package controlapi

import (
	"context"
	"maps"
	"slices"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/fieldmaskpb"
	"k8s.io/apimachinery/pkg/api/operation"
	"k8s.io/apimachinery/pkg/util/validation"
	"k8s.io/apimachinery/pkg/util/validation/field"
)

func toGRPCStatusError(errs field.ErrorList) error {
	return status.Error(codes.InvalidArgument, errs.ToAggregate().Error())
}

// Code generated by declarative vaidation will call this.
func ValidateCustom_WorkerAssignment_WorkerPodIp(_ context.Context, _ operation.Operation, fldPath *field.Path, value, _ *string) field.ErrorList {
	if value == nil {
		return nil
	}
	return validation.IsValidIP(fldPath, *value)
}

// Code generated by declarative vaidation will call this.
func ValidateCustom_UpdateActorRequest_UpdateMask(_ context.Context, _ operation.Operation, fldPath *field.Path, value, _ *fieldmaskpb.FieldMask) field.ErrorList {
	return validateUpdateMaskPaths(fldPath.Child("paths"), value.GetPaths(), actorMutableFields)
}

func validateUpdateMaskPaths[T any](fldPath *field.Path, maskPaths []string, validPaths mutableFields[T]) field.ErrorList {
	var errs field.ErrorList
	supported := slices.Sorted(maps.Keys(validPaths))
	for _, path := range maskPaths {
		if _, ok := validPaths[path]; !ok {
			errs = append(errs, field.NotSupported(fldPath, path, supported))
		}
	}
	return errs
}
